_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 33
                - 41
                - 49
                - 51
            "2":
                - 1
                - 33
                - 41
                - 49
                - 51
            "3":
                - 13
                - 16
                - 55
                - 61
            "4": 3.13.2
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-arm64
bs:
    value: 32
image_size:
    value: 256
lr:
    value: 0.0001
max_epochs:
    value: 10
max_examples:
    value: 100
weight_decay:
    value: 1e-06
